# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  job1:
    steps:
      - run: python --version           # For debugging
      - run: sudo apt-get update -qy    # updates the package lists to get information on the newest versions of packages and their dependencies

  job2:
    steps:
      - run: sudo apt-get install -y python3-pip
      - run: pip install virtualenv #start a virtual environment specifc to th project
      - run: virtualenv venv
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt #installtherequirementsfortheprojectitself.


# Defining circle-ci workflows and dependencies
workflows:
  version: 2.1
  jobs:
    - job1
    - job2:
        requires:
          - job1