version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: jdillarstone/my_image
        auth:
          username: jdillarstone
          password: cfd776ed-e16f-4426-a6f6-dd8aa30054dc # access token specific to this project
    steps:
      - run: python --version           # For debugging
      - run: apt-get update -qy    # updates the package lists to get information on the newest versions of packages and their dependencies

# Defining circle-ci workflows and dependencies
workflows:
  build:
    jobs:
      - build